# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "bullseye.local"
  config.vm.network "public_network"
  config.vm.synced_folder "./shared_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "bullseye64"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get dist-upgrade -y
  SHELL
end
