# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"
  config.vm.hostname = "alpine312.local"
  config.vm.network "public_network"
  config.vm.synced_folder "./shared_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine312"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk upgrade
  SHELL
end
