# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "xenial.local"
  config.vm.network "public_network"
  config.vm.synced_folder "./shared_data", "/vagrant_data"

  config.vm.provider "hyperv" do |hv|
    hv.vmname = "xenial"
    hv.memory = "2048"
    hv.cpus = 2
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "xenial"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get dist-upgrade -y
  SHELL
end
