# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7.local"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    yum -y upgrade
  SHELL
end
