# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.hostname = "rockylinux8.local"
  config.vm.network "public_network"
  config.vm.synced_folder "./shared_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rockylinux8"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    dnf -y upgrade
  SHELL
end
