# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "jammy.local"
  config.vm.network "public_network"
  config.vm.synced_folder "./shared_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jammy"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end
